DEVICE: "cuda:0"

DATASET:
  PATH: "/Users/jiawei/ENet-tuSimple/dataset/tusimple/full_set"
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  SIZE: [368,640]

TRAIN:
  MAX_EPOCHS: 300
  BATCH_SIZE: 16

TEST:
  BATCH_SIZE: 16

MODEL: 
  MOEL_NAME: "ENet"

OPTIM: 
  LR: 0.01
  DECAY: 0 
  

  
