DEVICE: "cuda:0"

DATASET:
  PATH: "/mnt/4TB/ngoj0003/ENet-tuSimple/data_tusimple/dataset"
  #MEAN: [0.485, 0.456, 0.406]
  #STD: [0.229, 0.224, 0.225]
  MEAN: [0.3598, 0.3653, 0.3662]
  STD: [0.2573, 0.2663, 0.2756]
  SIZE: [368,640]

TRAIN:
  MAX_EPOCHS: 400
  BATCH_SIZE: 12

TEST:
  BATCH_SIZE: 12

MODEL: 
  MOEL_NAME: "ENet"

OPTIM: 
  LR: 0.01
  DECAY: 0.0001
  

  
